FROM ubuntu:16.04

RUN apt-get -y update && apt-get install -y unattended-upgrades

# add postgres sources
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" > /etc/apt/sources.list.d/pgdg.list

# install pubkeys and postgres
RUN apt-get install -y wget ca-certificates &&\
	wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - &&\
	apt-get update &&\
	apt-get -y upgrade &&\
	apt-get install -y python-software-properties software-properties-common postgresql-9.3 postgresql-client-9.3 postgresql-contrib-9.3

USER postgres

RUN /etc/init.d/postgresql start &&\
    psql --command "CREATE USER papu WITH SUPERUSER PASSWORD 'uutoyai4wai&xaiX';" &&\
    createdb -O papu_prod papu &&\
		createdb -O papu_dev papu &&\
		createdb -O papu_test papu

# Adjust PostgreSQL configuration so that remote connections to the
# database are possible.
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.3/main/pg_hba.conf

# And add ``listen_addresses`` to ``/etc/postgresql/9.3/main/postgresql.conf``
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.3/main/postgresql.conf

# Expose the PostgreSQL port
EXPOSE 5432

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

# Set the default command to run when starting the container
CMD ["/usr/lib/postgresql/9.3/bin/postgres", "-D", "/var/lib/postgresql/9.3/main", "-c", "config_file=/etc/postgresql/9.3/main/postgresql.conf"]

# add user
RUN useradd -ms /bin/bash papu

USER papu
WORKDIR /home/papu

RUN apt-get install -y git

RUN git clone https://github.com/ciudadanointeligente/partidopublico.git

WORKDIR /home/papu/partidopublico

# pubkey rvm
RUN gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

# install rvm
RUN \curl -sSL https://get.rvm.io | bash -s stable


RUN bundle install

RUN rake db:setup ENV=production
RUN rake db:setup ENV=development
